---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.0
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.0
  armhf: ghcr.io/hassio-addons/base/armhf:15.0.0
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.0
