---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:18.1.1
  amd64: ghcr.io/hassio-addons/base/amd64:18.1.1
  armhf: ghcr.io/hassio-addons/base/armhf:18.1.1
  armv7: ghcr.io/hassio-addons/base/armv7:18.1.1
